/**
 * Article provenance — captures model identity, generation timestamp,
 * and network path to the API endpoint for transparency disclaimers.
 */

import { execSync } from "node:child_process";

export interface NetworkHop {
  hop: number;
  host: string;
  loss: string;
  latency: string;
}

export interface Provenance {
  model: string;
  provider: "anthropic" | "openai";
  generatedAt: string;
  apiHost: string;
  networkPath: NetworkHop[];
}

/** IPs and prefixes to redact from network traces */
const REDACT_PATTERNS = [
  /^10\.\d+\.\d+\.\d+/,          // RFC1918 class A
  /^172\.(1[6-9]|2\d|3[01])\./,  // RFC1918 class B
  /^192\.168\./,                   // RFC1918 class C
  /^24\.112\./,                    // Vyve subscriber space
  /^100\.(6[4-9]|[7-9]\d|1[0-2]\d)\./, // CGNAT
];

function shouldRedact(ip: string): boolean {
  return REDACT_PATTERNS.some((p) => p.test(ip));
}

/** Parse MTR report output into structured hops */
function parseMtrReport(raw: string): NetworkHop[] {
  const hops: NetworkHop[] = [];
  const lines = raw.split("\n");

  for (const line of lines) {
    // MTR report format: "  N.|-- hostname    Loss%   Snt   Last   Avg  Best  Wrst StDev"
    const match = line.match(
      /^\s*(\d+)\.\|--\s+(\S+)\s+(\S+)%\s+\d+\s+[\d.]+\s+([\d.]+)/
    );
    if (!match) continue;

    const [, hopNum, host, loss, avg] = match;
    let displayHost = host;

    // Redact sensitive IPs
    if (host === "???" || host === "???") {
      displayHost = "???";
    } else if (shouldRedact(host)) {
      displayHost = "[REDACTED]";
    }

    hops.push({
      hop: parseInt(hopNum),
      host: displayHost,
      loss: `${loss}%`,
      latency: `${avg}ms`,
    });
  }

  return hops;
}

/** Run MTR trace to a host, return parsed hops */
export function traceNetworkPath(host: string): NetworkHop[] {
  try {
    const raw = execSync(
      `mtr --report --report-cycles 3 --no-dns ${host} 2>/dev/null || traceroute -n -m 20 -q 1 ${host} 2>/dev/null || echo "trace unavailable"`,
      { timeout: 30_000, encoding: "utf-8" }
    );

    if (raw.includes("trace unavailable") || !raw.trim()) {
      return [{ hop: 0, host: "(trace unavailable on this runner)", loss: "-", latency: "-" }];
    }

    // If we got traceroute output instead of mtr
    if (!raw.includes("|--")) {
      return parseTraceroute(raw);
    }

    return parseMtrReport(raw);
  } catch {
    return [{ hop: 0, host: "(trace failed — insufficient privileges or tool not installed)", loss: "-", latency: "-" }];
  }
}

/** Fallback parser for standard traceroute output */
function parseTraceroute(raw: string): NetworkHop[] {
  const hops: NetworkHop[] = [];
  for (const line of raw.split("\n")) {
    const match = line.match(/^\s*(\d+)\s+(\S+)\s+([\d.]+)\s*ms/);
    if (!match) continue;
    const [, hopNum, host, latency] = match;
    let displayHost = host;
    if (host === "*") displayHost = "???";
    else if (shouldRedact(host)) displayHost = "[REDACTED]";

    hops.push({
      hop: parseInt(hopNum),
      host: displayHost,
      loss: "-",
      latency: `${latency}ms`,
    });
  }
  return hops;
}

/** Format network path as markdown table */
function formatNetworkPath(hops: NetworkHop[]): string {
  if (hops.length === 0) return "*Network trace not available*";
  if (hops[0].host.startsWith("(")) return `*${hops[0].host}*`;

  const lines = [
    "| Hop | Host | Loss | Avg Latency |",
    "|-----|------|------|-------------|",
  ];
  for (const h of hops) {
    lines.push(`| ${h.hop} | ${h.host} | ${h.loss} | ${h.latency} |`);
  }
  return lines.join("\n");
}

/** Build the full provenance disclaimer for an article footer */
export function formatProvenance(p: Provenance): string {
  const networkTable = formatNetworkPath(p.networkPath);

  return `---

<details>
<summary><strong>Article Provenance</strong></summary>

This article was generated by an LLM. Full transparency on what produced it:

| | |
|---|---|
| **Model** | \`${p.model}\` |
| **Provider** | ${p.provider === "anthropic" ? "Anthropic" : "OpenAI"} |
| **Generated** | ${p.generatedAt} |
| **API Host** | ${p.apiHost} |

### Network path to API at generation time

${networkTable}

Sensitive IP addresses (source, LAN, subscriber) are redacted.

</details>`;
}

/** Resolve the API host for a provider */
export function apiHostForProvider(provider: "anthropic" | "openai"): string {
  return provider === "anthropic" ? "api.anthropic.com" : "api.openai.com";
}
